=== Dahlia-Chehata/DBMS-JDBC/Class/students.dtd
<!ELEMENT students (ColumnNames,DataTypes,Column+)>
<!ELEMENT ColumnNames (Col1,Col2,Col3)>
<!ELEMENT Col1 (#PCDATA)>
<!ELEMENT Col2 (#PCDATA)>
<!ELEMENT Col3 (#PCDATA)>
<!ELEMENT DataTypes (Type1,Type2,Type3)>
<!ELEMENT Type1 (#PCDATA)>
<!ELEMENT Type2 (#PCDATA)>
<!ELEMENT Type3 (#PCDATA)>
<!ELEMENT Column (Cell1,Cell2,Cell3,Cell4,Cell5,Cell6)>
<!ELEMENT Cell1 (#PCDATA)>
<!ELEMENT Cell2 (#PCDATA)>
<!ELEMENT Cell3 (#PCDATA)>
<!ELEMENT Cell4 (#PCDATA)>
<!ELEMENT Cell5 (#PCDATA)>
<!ELEMENT Cell6 (#PCDATA)>

=== Dahlia-Chehata/DBMS-JDBC/bin/Class/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
  <ColumnNames>
    <Col1>ID</Col1>
    <Col2>Name</Col2>
    <Col3>grades</Col3>
  </ColumnNames>
  <DataTypes>
    <Type1>int</Type1>
    <Type2>String</Type2>
    <Type3>int</Type3>
  </DataTypes>
  <Column>
    <Cell1>1</Cell1>
    <Cell2>2</Cell2>
    <Cell3>3</Cell3>
    <Cell4>4</Cell4>
    <Cell5>4</Cell5>
    <Cell6>5</Cell6>
  </Column>
  <Column>
    <Cell1>Mohamed</Cell1>
    <Cell2>Reem</Cell2>
    <Cell3>Hoda</Cell3>
    <Cell4>Jojo</Cell4>
    <Cell5>Nada</Cell5>
    <Cell6>Reem</Cell6>
  </Column>
  <Column>
    <Cell1>100</Cell1>
    <Cell2>200</Cell2>
    <Cell3>50</Cell3>
    <Cell4>75</Cell4>
    <Cell5>70</Cell5>
    <Cell6>200</Cell6>
  </Column>
</students>

=== Dahlia-Chehata/DBMS-JDBC/university/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
  <ColumnNames>
    <Col1>sid</Col1>
    <Col2>fname</Col2>
    <Col3>lname</Col3>
  </ColumnNames>
  <DataTypes>
    <Type1>int</Type1>
    <Type2>String</Type2>
    <Type3>String</Type3>
  </DataTypes>
  <Column>
    <Cell1>1</Cell1>
    <Cell2>2</Cell2>
    <Cell3>3</Cell3>
    <Cell4>4</Cell4>
  </Column>
  <Column>
    <Cell1>Mickey</Cell1>
    <Cell2>Minnie</Cell2>
    <Cell3>Donald</Cell3>
    <Cell4>Goofy</Cell4>
  </Column>
  <Column>
    <Cell1>Mouse</Cell1>
    <Cell2>Mouse</Cell2>
    <Cell3>Duck</Cell3>
    <Cell4>Goof</Cell4>
  </Column>
</students>
